<?php

namespace TYPO3\Flow\Persistence\Doctrine\Proxies\__CG__\Project\Helpiez\Domain\Model;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Organisation extends \Project\Helpiez\Domain\Model\Organisation implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function __wakeup()
    {
        $this->__load();
        return parent::__wakeup();
    }

    public function Flow_Aop_Proxy_fixMethodsAndAdvicesArrayForDoctrineProxies()
    {
        $this->__load();
        return parent::Flow_Aop_Proxy_fixMethodsAndAdvicesArrayForDoctrineProxies();
    }

    public function Flow_Aop_Proxy_fixInjectedPropertiesForDoctrineProxies()
    {
        $this->__load();
        return parent::Flow_Aop_Proxy_fixInjectedPropertiesForDoctrineProxies();
    }

    public function Flow_Aop_Proxy_invokeJoinPoint(\TYPO3\Flow\Aop\JoinPointInterface $joinPoint)
    {
        $this->__load();
        return parent::Flow_Aop_Proxy_invokeJoinPoint($joinPoint);
    }

    public function getTags()
    {
        $this->__load();
        return parent::getTags();
    }

    public function setTags($tags)
    {
        $this->__load();
        return parent::setTags($tags);
    }

    public function getTimestamp()
    {
        $this->__load();
        return parent::getTimestamp();
    }

    public function setTimestamp($timestamp = NULL)
    {
        $this->__load();
        return parent::setTimestamp($timestamp);
    }

    public function updatedTimestamps()
    {
        $this->__load();
        return parent::updatedTimestamps();
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getAddress()
    {
        $this->__load();
        return parent::getAddress();
    }

    public function setAddress($address)
    {
        $this->__load();
        return parent::setAddress($address);
    }

    public function getRegion()
    {
        $this->__load();
        return parent::getRegion();
    }

    public function setRegion($region)
    {
        $this->__load();
        return parent::setRegion($region);
    }

    public function getNumber()
    {
        $this->__load();
        return parent::getNumber();
    }

    public function setNumber($number)
    {
        $this->__load();
        return parent::setNumber($number);
    }

    public function getWebsite()
    {
        $this->__load();
        return parent::getWebsite();
    }

    public function setWebsite($website)
    {
        $this->__load();
        return parent::setWebsite($website);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getYoutube()
    {
        $this->__load();
        return parent::getYoutube();
    }

    public function setYoutube($youtube)
    {
        $this->__load();
        return parent::setYoutube($youtube);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getFb()
    {
        $this->__load();
        return parent::getFb();
    }

    public function setFb($fb)
    {
        $this->__load();
        return parent::setFb($fb);
    }

    public function getBlogurl()
    {
        $this->__load();
        return parent::getBlogurl();
    }

    public function setBlogurl($blogurl)
    {
        $this->__load();
        return parent::setBlogurl($blogurl);
    }

    public function getTwitter()
    {
        $this->__load();
        return parent::getTwitter();
    }

    public function setTwitter($twitter)
    {
        $this->__load();
        return parent::setTwitter($twitter);
    }

    public function getCause()
    {
        $this->__load();
        return parent::getCause();
    }

    public function setCause($cause)
    {
        $this->__load();
        return parent::setCause($cause);
    }

    public function getBeneficiary()
    {
        $this->__load();
        return parent::getBeneficiary();
    }

    public function setBeneficiary($beneficiary)
    {
        $this->__load();
        return parent::setBeneficiary($beneficiary);
    }

    public function getQuote()
    {
        $this->__load();
        return parent::getQuote();
    }

    public function setQuote($quote)
    {
        $this->__load();
        return parent::setQuote($quote);
    }

    public function getPageViews()
    {
        $this->__load();
        return parent::getPageViews();
    }

    public function setPageViews($pageViews)
    {
        $this->__load();
        return parent::setPageViews($pageViews);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }


    public function __sleep()
    {
        return array_merge(array('__isInitialized__'), parent::__sleep());
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        parent::__clone();
    }
}