#                                                                        #
# Default subroutes configuration for the Project.Helpiez package             #
#                                                                        #

##
# Authentication

-
  name:  'Authentication'
  uriPattern: 'auth/<AuthenticationSubRoutes>'
  defaults:
    '@package':    'Project.Helpiez'
    '@controller': 'Auth'
    '@action':     'index'
    '@format':     'html'
  subRoutes:
    'AuthenticationSubRoutes':
      package: 'Project.Helpiez'
      suffix:  'Authentication'

##
# Backend Post

-
  name:  'Backend Post'
  uriPattern: 'backend/post/<BackendSubRoutes>'
  defaults:
    '@package':    'Project.Helpiez'
    '@controller': 'Backend\post'
    '@action':     'home'
    '@format':     'html'
  subRoutes:
    'BackendSubRoutes':
      package: 'Project.Helpiez'
      suffix:  'PostBackend'

##
# Backend Get

-
  name:  'Backend Get'
  uriPattern: 'backend/<BackendSubRoutes>'
  defaults:
    '@package':    'Project.Helpiez'
    '@controller': 'Backend\Get'
    '@action':     'home'
    '@format':     'html'
  subRoutes:
    'BackendSubRoutes':
      package: 'Project.Helpiez'
      suffix:  'GetBackend'

##
# Frontend Post

-
  name:  'Frontend Post'
  uriPattern: 'post/<FrontendSubRoutes>'
  defaults:
    '@package':    'Project.Helpiez'
    '@controller': 'Frontend\Post'
    '@action':     'show'
    '@format':     'html'
  subRoutes:
    'FrontendSubRoutes':
      package: 'Project.Helpiez'
      suffix:  'PostFrontend'
  httpMethods: ['POST']

##
# Frontend Get

-
  name:  'Frontend Get'
  uriPattern: '<FrontendSubRoutes>'
  defaults:
    '@package':    'Project.Helpiez'
    '@controller': 'Frontend\Get'
    '@action':     'home'
    '@format':     'html'
  subRoutes:
    'FrontendSubRoutes':
      package: 'Project.Helpiez'
      suffix:  'GetFrontend'